"""Core data structures for auto-sharding."""

import dataclasses

from keras.src.distribution.distribution_lib import LayoutMap


@dataclasses.dataclass
class ShardingPlan:
    """A data structure to hold the results of an auto-sharding analysis.

    This plan is generated by an `IShardingPlanner` and consumed by an
    `IShardApplier`. It contains the layout decisions for all variables.

    Attributes:
        layout_map: A `LayoutMap` that maps variable paths to their computed
            `TensorLayout`.
    """

    layout_map: LayoutMap
